version: '3.6'

services:

  scirius-backend:
    image: markuskont/scirius-backend
    build: backend/
    #hostname: CDMCS

    volumes:
      - scirius-sockets:/var/run/scirius
      - scirius-static:/opt/scirius/static
    environment:
      ELASTICSEARCH_ADDRESS: ${ELASTICSEARCH_ADDRESS}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SURICATA_UNIX_SOCKET: ${SURICATA_UNIX_SOCKET}

  scirius-proxy:
    image: markuskont/scirius-proxy
    build: proxy/
    volumes:
      - scirius-sockets:/var/run/scirius
      - scirius-static:/opt/scirius/static
    ports:
      - 8000:80

volumes:
  scirius-sockets:
    driver: local
  scirius-static:
    driver: local
