#!/usr/bin/env python
import os

ELASTICSEARCH_LOGSTASH_INDEX = "suricata-"
ELASTICSEARCH_LOGSTASH_ALERT_INDEX = "suricata-"
ELASTICSEARCH_VERSION = os.environ["ELASTICSEARCH_VERSION"] if "ELASTICSEARCH_VERSION" in os.environ else 7
ELASTICSEARCH_KEYWORD = "keyword"
ELASTICSEARCH_LOGSTASH_TIMESTAMPING = os.environ['ELASTICSEARCH_LOGSTASH_TIMESTAMPING'] if "ELASTICSEARCH_LOGSTASH_TIMESTAMPING" in os.environ else "daily"
ELASTICSEARCH_ADDRESS = os.environ['ELASTICSEARCH_ADDRESS'] if "ELASTICSEARCH_ADDRESS" in os.environ else "elasticsearch:9200"

ALLOWED_HOSTS = os.environ['ALLOWED_HOSTS'].split(",") if "ALLOWED_HOSTS" in os.environ else ["localhost"]
SURICATA_NAME_IS_HOSTNAME = False
#SURICATA_NAME_IS_HOSTNAME = True
SURICATA_UNIX_SOCKET = os.environ['SURICATA_UNIX_SOCKET'] if "SURICATA_UNIX_SOCKET" in os.environ else None

#USE_KIBANA = True
#KIBANA_URL = "http://$EXPOSE:5601"
#KIBANA_INDEX = ".kibana"
#USE_EVEBOX = True
#EVEBOX_ADDRESS = "$EXPOSE:5636"
